export const actionType = {
  // auth
  SET_LOGIN: "SET_LOGIN",

  // projects
  SET_PROJECT_LIST: "SET_PROJECT_LIST",
  SET_PROJECT_CATEGORIES: "SET_PROJECT_CATEGORIES",
  SET_PROJECT_ERROR: "SET_PROJECT_ERROR",
  SET_PROJECT_MEMBERS: "SET_PROJECT_MEMBERS",
  SET_PROJECT_DETAIL: "SET_PROJECT_DETAIL",

  // tasks

  // users
  SET_USER_LIST: "SET_USER_LIST",
};
