export const actionType = {
  // auth
  SET_LOGIN: "SET_LOGIN",

  // projects
  SET_PROJECT_LIST: "SET_PROJECT_LIST",
  SET_PROJECT_CATEGORIES: "SET_PROJECT_CATEGORIES",
  SET_PROJECT_ERROR: "SET_PROJECT_ERROR",
  SET_PROJECT_MEMBERS: "SET_PROJECT_MEMBERS",
  SET_PROJECT_DETAIL: "SET_PROJECT_DETAIL",
  SET_PROJECT_EDIT_INFO: "SET_PROJECT_EDIT_INFO",

  // tasks
  SET_TASK_TYPES: "SET_TASK_TYPES",
  SET_TASK_DETAIL: "SET_TASK_DETAIL",
  SET_TASK_ERROR: "SET_TASK_ERROR",

  // users
  SET_USER_LIST: "SET_USER_LIST",
  
};
